package d.model.pojos;
// Generated 11/05/2022 06:31:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer id;
     private Area area;
     private Cargo cargo;
     private String nombre;
     private String apellido;
     private Integer edad;
     private Date fechaIngreso;
     private Integer casillero;
     private Set usuarioses = new HashSet(0);

    public Empleado() {
    }

    public Empleado(Area area, Cargo cargo, String nombre, String apellido, Integer edad, Date fechaIngreso, Integer casillero, Set usuarioses) {
       this.area = area;
       this.cargo = cargo;
       this.nombre = nombre;
       this.apellido = apellido;
       this.edad = edad;
       this.fechaIngreso = fechaIngreso;
       this.casillero = casillero;
       this.usuarioses = usuarioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Integer getCasillero() {
        return this.casillero;
    }
    
    public void setCasillero(Integer casillero) {
        this.casillero = casillero;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


