package d.model.pojos;
// Generated 11/05/2022 06:31:47 PM by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer id;
     private Empleado empleado;
     private String usuario;
     private String password;

    public Usuarios() {
    }

	
    public Usuarios(String usuario, String password) {
        this.usuario = usuario;
        this.password = password;
    }
    public Usuarios(Empleado empleado, String usuario, String password) {
       this.empleado = empleado;
       this.usuario = usuario;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


